# syntax=docker/dockerfile:1
FROM node:24.4.0-slim AS base
ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"
RUN apt-get update \
    && apt-get install -y --no-install-recommends bash ca-certificates curl unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -fsSL https://bun.sh/install | bash -s -- bun-v1.3.14 \
    && ln -sf "$BUN_INSTALL/bin/bun" "$BUN_INSTALL/bin/bunx"

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y python3 make g++ git python3-pip pkg-config libsecret-1-dev && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN --mount=type=cache,id=bun,target=/root/.bun/install/cache bun install --frozen-lockfile

# Deploy only the dokploy app

ENV NODE_ENV=production
RUN bun run --filter './packages/server' build
RUN bun run --filter './apps/schedules' build

RUN bun install --production --frozen-lockfile --linker hoisted

RUN mkdir -p /prod/schedules \
    && cp -R /usr/src/app/apps/schedules/package.json /prod/schedules/package.json \
    && cp -R /usr/src/app/node_modules /prod/schedules/node_modules \
    && mkdir -p /prod/schedules/packages \
    && cp -R /usr/src/app/packages/server /prod/schedules/packages/server \
    && rm -f /prod/schedules/node_modules/dokploy \
    && rm -f /prod/schedules/node_modules/@dokploy/api \
    && rm -f /prod/schedules/node_modules/@dokploy/schedules

RUN cp -R /usr/src/app/apps/schedules/dist /prod/schedules/dist

FROM base AS dokploy
WORKDIR /app

# Set production
ENV NODE_ENV=production

# Copy only the necessary files
COPY --from=build /prod/schedules/dist ./dist
COPY --from=build /prod/schedules/package.json ./package.json
COPY --from=build /prod/schedules/node_modules ./node_modules
COPY --from=build /prod/schedules/packages ./packages

ENV HOSTNAME=0.0.0.0
CMD ["bun", "run", "start"]
