# syntax=docker/dockerfile:1
FROM oven/bun:1.3.14 AS bun

FROM node:24.4.0-slim AS base
COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun
ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"
RUN ln -s /usr/local/bin/bun /usr/local/bin/bunx

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y python3 make g++ git python3-pip pkg-config libsecret-1-dev && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN --mount=type=cache,id=bun,target=/root/.bun/install/cache bun install --frozen-lockfile


# Deploy only the dokploy app
# ARG NEXT_PUBLIC_UMAMI_HOST
# ENV NEXT_PUBLIC_UMAMI_HOST=$NEXT_PUBLIC_UMAMI_HOST

# ARG NEXT_PUBLIC_UMAMI_WEBSITE_ID
# ENV NEXT_PUBLIC_UMAMI_WEBSITE_ID=$NEXT_PUBLIC_UMAMI_WEBSITE_ID

ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

ENV NODE_ENV=production
RUN bun run --filter './packages/server' build
RUN bun run --filter './apps/dokploy' build

RUN bun install --production --frozen-lockfile --linker hoisted

RUN mkdir -p /prod/dokploy \
    && cp -R /usr/src/app/apps/dokploy/package.json /prod/dokploy/package.json \
    && cp -R /usr/src/app/apps/dokploy/next.config.mjs /prod/dokploy/next.config.mjs \
    && cp -R /usr/src/app/apps/dokploy/public /prod/dokploy/public \
    && cp -R /usr/src/app/apps/dokploy/drizzle /prod/dokploy/drizzle \
    && cp -R /usr/src/app/apps/dokploy/components.json /prod/dokploy/components.json \
    && cp -R /usr/src/app/node_modules /prod/dokploy/node_modules \
    && mkdir -p /prod/dokploy/packages \
    && cp -R /usr/src/app/packages/server /prod/dokploy/packages/server \
    && rm -f /prod/dokploy/node_modules/dokploy \
    && rm -f /prod/dokploy/node_modules/@dokploy/api \
    && rm -f /prod/dokploy/node_modules/@dokploy/schedules

RUN cp -R /usr/src/app/apps/dokploy/.next /prod/dokploy/.next
RUN cp -R /usr/src/app/apps/dokploy/dist /prod/dokploy/dist

FROM base AS dokploy
WORKDIR /app

# Set production
ENV NODE_ENV=production

RUN apt-get update && apt-get install -y curl unzip apache2-utils && rm -rf /var/lib/apt/lists/*

# Copy only the necessary files
COPY --from=build /prod/dokploy/.next ./.next
COPY --from=build /prod/dokploy/dist ./dist
COPY --from=build /prod/dokploy/next.config.mjs ./next.config.mjs
COPY --from=build /prod/dokploy/public ./public
COPY --from=build /prod/dokploy/package.json ./package.json
COPY --from=build /prod/dokploy/drizzle ./drizzle
COPY --from=build /prod/dokploy/components.json ./components.json
COPY --from=build /prod/dokploy/node_modules ./node_modules
COPY --from=build /prod/dokploy/packages ./packages


# Install RCLONE
RUN curl https://rclone.org/install.sh | bash

# tsx
RUN bun install -g tsx

EXPOSE 3000
CMD ["bun", "run", "start"]
