import { db } from "@dokploy/server/db";
import { backups, schedules } from "@dokploy/server/db/schema";
import type { SuperSessionAccessKind } from "@dokploy/server/services/super-password";
import { eq } from "drizzle-orm";

type ProcedureAccessCtx = {
	user: { id: string; email?: string | null };
};

type ConditionalAccess = {
	dangerousWhen: (
		input: unknown,
		ctx: ProcedureAccessCtx,
	) => boolean | Promise<boolean>;
};

/**
 * Super password classification of every tRPC procedure in the app router.
 *
 * - "read": allowed for browser sessions and API keys.
 * - "write": allowed for browser sessions; API keys of a user with a super
 *   password need an open super session.
 * - "dangerous": a user with a super password needs a browser session and an
 *   open super session; API keys can never call it.
 *
 * Users without a super password keep today's behaviour. The router test in
 * __test__/security/super-session-procedure-access.test.ts fails when a
 * procedure is missing here, so procedures added by upstream merges must be
 * classified before they ship. Some procedures also check the super session
 * themselves for part of their input (Traefik TLS files, panel system
 * containers and volumes).
 */
export type ProcedureAccess = SuperSessionAccessKind | ConditionalAccess;

const asRecord = (input: unknown) =>
	input && typeof input === "object" ? (input as Record<string, unknown>) : {};

const changesLoginCredentials = (input: unknown, ctx: ProcedureAccessCtx) => {
	const { email, password, currentPassword } = asRecord(input);
	if (password || currentPassword) {
		return true;
	}
	return (
		typeof email === "string" &&
		email.trim().toLowerCase() !== (ctx.user.email ?? "").trim().toLowerCase()
	);
};

const isHostScheduleInput = (input: unknown) =>
	asRecord(input).scheduleType === "dokploy-server";

const isStoredHostSchedule = async (input: unknown) => {
	const { scheduleId } = asRecord(input);
	if (typeof scheduleId !== "string") {
		return false;
	}
	const schedule = await db.query.schedules.findFirst({
		where: eq(schedules.scheduleId, scheduleId),
		columns: { scheduleType: true },
	});
	return schedule?.scheduleType === "dokploy-server";
};

// A web server backup is a dump of the panel database, which stores every
// secret in clear.
const isWebServerBackupInput = (input: unknown) =>
	asRecord(input).databaseType === "web-server";

const isWebServerBackupUpdate = async (input: unknown) => {
	if (isWebServerBackupInput(input)) {
		return true;
	}
	const { backupId } = asRecord(input);
	if (typeof backupId !== "string") {
		return false;
	}
	const backup = await db.query.backups.findFirst({
		where: eq(backups.backupId, backupId),
		columns: { databaseType: true },
	});
	return backup?.databaseType === "web-server";
};

export const PROCEDURE_ACCESS: Record<string, ProcedureAccess> = {
	"admin.setupMonitoring": "write",
	"ai.analyzeLogs": "write",
	"ai.create": "write",
	"ai.delete": "write",
	"ai.deploy": "write",
	"ai.get": "read",
	"ai.getAll": "read",
	"ai.getCustomProviders": "read",
	"ai.getEnabledProviders": "read",
	"ai.getModels": "read",
	"ai.one": "read",
	"ai.saveCustomProviders": "write",
	"ai.suggest": "write",
	"ai.testConnection": "write",
	"ai.update": "write",
	"application.cancelDeployment": "write",
	"application.cleanQueues": "write",
	"application.clearDeployments": "write",
	"application.create": "write",
	"application.delete": "dangerous",
	"application.deploy": "write",
	"application.deployNginxQuickstart": "write",
	"application.disconnectGitProvider": "write",
	"application.dropDeployment": "write",
	"application.envUpsert": "write",
	"application.killBuild": "write",
	"application.markRunning": "write",
	"application.move": "write",
	"application.one": "read",
	"application.readAppMonitoring": "read",
	"application.readLogs": "read",
	"application.readTraefikConfig": "read",
	"application.redeploy": "write",
	"application.refreshToken": "write",
	"application.reload": "write",
	"application.revealEnvironment": "dangerous",
	"application.saveBitbucketProvider": "write",
	"application.saveBuildType": "write",
	"application.saveDockerProvider": "write",
	"application.saveEnvironment": "write",
	"application.saveGitProvider": "write",
	"application.saveGiteaProvider": "write",
	"application.saveGithubProvider": "write",
	"application.saveGitlabProvider": "write",
	"application.search": "read",
	"application.start": "write",
	"application.stop": "write",
	"application.update": "write",
	"application.updateTraefikConfig": "write",
	"auditLog.all": "read",
	"backup.create": { dangerousWhen: isWebServerBackupInput },
	"backup.listBackupFiles": "read",
	"backup.manualBackupCompose": "write",
	"backup.manualBackupLibsql": "write",
	"backup.manualBackupMariadb": "write",
	"backup.manualBackupMongo": "write",
	"backup.manualBackupMySql": "write",
	"backup.manualBackupPostgres": "write",
	"backup.manualBackupWebServer": "dangerous",
	"backup.one": "read",
	"backup.remove": "write",
	"backup.restoreBackupWithLogs": "dangerous",
	"backup.update": { dangerousWhen: isWebServerBackupUpdate },
	"bitbucket.bitbucketProviders": "read",
	"bitbucket.create": "write",
	"bitbucket.getBitbucketBranches": "read",
	"bitbucket.getBitbucketRepositories": "read",
	"bitbucket.one": "read",
	"bitbucket.testConnection": "write",
	"bitbucket.update": "write",
	"certificates.all": "read",
	"certificates.create": "write",
	"certificates.one": "read",
	"certificates.remove": "dangerous",
	"certificates.update": "write",
	"cluster.addManager": "dangerous",
	"cluster.addWorker": "dangerous",
	"cluster.getNodes": "read",
	"cluster.removeWorker": "write",
	"compose.cancelDeployment": "write",
	"compose.cleanQueues": "write",
	"compose.clearDeployments": "write",
	"compose.create": "write",
	"compose.delete": "dangerous",
	"compose.deploy": "write",
	"compose.deployExact": "write",
	"compose.deployTemplate": "write",
	"compose.disconnectGitProvider": "write",
	"compose.env.upsert": "write",
	"compose.fetchSourceType": "write",
	"compose.getConvertedCompose": "read",
	"compose.getDefaultCommand": "read",
	"compose.getTags": "read",
	"compose.import": "write",
	"compose.isolatedDeployment": "write",
	"compose.killBuild": "write",
	"compose.loadMountsByService": "read",
	"compose.loadServices": "read",
	"compose.move": "write",
	"compose.one": "read",
	"compose.previewTemplate": "write",
	"compose.processTemplate": "write",
	"compose.randomizeCompose": "write",
	"compose.readLogs": "read",
	"compose.redeploy": "write",
	"compose.refreshToken": "write",
	"compose.revealEnvironment": "dangerous",
	"compose.saveEnvironment": "write",
	"compose.search": "read",
	"compose.start": "write",
	"compose.stop": "write",
	"compose.templates": "read",
	"compose.update": "write",
	"customRole.all": "read",
	"customRole.create": "dangerous",
	"customRole.getStatements": "read",
	"customRole.membersByRole": "read",
	"customRole.remove": "dangerous",
	"customRole.update": "dangerous",
	"deployment.all": "read",
	"deployment.allByCompose": "read",
	"deployment.allByServer": "read",
	"deployment.allByType": "read",
	"deployment.allCentralized": "read",
	"deployment.killProcess": "write",
	"deployment.queueList": "read",
	"deployment.readLogs": "read",
	"deployment.reconcile": "write",
	"deployment.removeDeployment": "write",
	"destination.all": "read",
	"destination.create": "write",
	"destination.one": "read",
	"destination.remove": "dangerous",
	"destination.testConnection": "write",
	"destination.update": "write",
	"dnsProvider.all": "read",
	"dnsProvider.create": "write",
	"dnsProvider.createRecord": "write",
	"dnsProvider.deleteRecord": "write",
	"dnsProvider.listRecords": "read",
	"dnsProvider.listZones": "read",
	"dnsProvider.one": "read",
	"dnsProvider.remove": "write",
	"dnsProvider.testConnection": "write",
	"dnsProvider.update": "write",
	"dnsProvider.updateRecord": "write",
	"docker.deleteContainerFile": "write",
	"docker.getConfig": "dangerous",
	"docker.getContainers": "read",
	"docker.getContainersByAppLabel": "read",
	"docker.getContainersByAppNameMatch": "read",
	"docker.getEvents": "read",
	"docker.getServerHealth": "read",
	"docker.getServiceContainersByAppName": "read",
	"docker.getStackContainersByAppName": "read",
	"docker.killContainer": "write",
	"docker.listContainerFiles": "write",
	"docker.readContainerFile": "write",
	"docker.removeContainer": "write",
	"docker.restartContainer": "write",
	"docker.startContainer": "write",
	"docker.stopContainer": "write",
	"docker.uploadFileToContainer": "write",
	"docker.writeContainerFile": "write",
	"dockerDiskUsage.getBuildCache": "read",
	"dockerDiskUsage.getDiskUsage": "read",
	"dockerDiskUsage.pruneBuildCache": "write",
	"dockerImage.getImageConfig": "read",
	"dockerImage.getImages": "read",
	"dockerImage.removeImage": "write",
	"dockerVolume.deleteVolumeFile": "write",
	"dockerVolume.getVolumeConfig": "read",
	"dockerVolume.getVolumes": "read",
	"dockerVolume.getVolumesSize": "read",
	"dockerVolume.listVolumeFiles": "write",
	"dockerVolume.readVolumeFile": "write",
	"dockerVolume.removeVolume": "dangerous",
	"dockerVolume.writeVolumeFile": "write",
	"domain.byApplicationId": "read",
	"domain.byComposeId": "read",
	"domain.canGenerateTraefikMeDomains": "read",
	"domain.create": "write",
	"domain.delete": "write",
	"domain.generateDomain": "write",
	"domain.one": "read",
	"domain.toggleEnable": "write",
	"domain.update": "write",
	"domain.validateDomain": "write",
	"environment.byProjectId": "read",
	"environment.create": "write",
	"environment.duplicate": "write",
	"environment.one": "read",
	"environment.remove": "dangerous",
	"environment.search": "read",
	"environment.update": "write",
	"forwardAuth.deployOnServer": "dangerous",
	"forwardAuth.disable": "dangerous",
	"forwardAuth.enable": "dangerous",
	"forwardAuth.getAuthDomain": "read",
	"forwardAuth.listProviders": "read",
	"forwardAuth.removeAuthDomain": "dangerous",
	"forwardAuth.removeOnServer": "dangerous",
	"forwardAuth.serverStatus": "read",
	"forwardAuth.setAuthDomain": "dangerous",
	"forwardAuth.status": "read",
	"gitProvider.allForPermissions": "read",
	"gitProvider.getAll": "read",
	"gitProvider.remove": "dangerous",
	"gitProvider.toggleShare": "write",
	"gitea.create": "write",
	"gitea.getGiteaBranches": "read",
	"gitea.getGiteaRepositories": "read",
	"gitea.getGiteaUrl": "read",
	"gitea.giteaProviders": "read",
	"gitea.one": "read",
	"gitea.testConnection": "write",
	"gitea.update": "write",
	"github.appSetupState": "read",
	"github.getGithubBranches": "read",
	"github.getGithubRepositories": "read",
	"github.githubProviders": "read",
	"github.one": "read",
	"github.testConnection": "write",
	"github.update": "write",
	"gitlab.create": "write",
	"gitlab.getGitlabBranches": "read",
	"gitlab.getGitlabRepositories": "read",
	"gitlab.gitlabProviders": "read",
	"gitlab.one": "read",
	"gitlab.testConnection": "write",
	"gitlab.update": "write",
	"libsql.changeStatus": "write",
	"libsql.create": "write",
	"libsql.deploy": "write",
	"libsql.deployWithLogs": "write",
	"libsql.move": "write",
	"libsql.one": "read",
	"libsql.readLogs": "read",
	"libsql.rebuild": "write",
	"libsql.reload": "write",
	"libsql.remove": "dangerous",
	"libsql.revealEnvironment": "dangerous",
	"libsql.saveEnvironment": "write",
	"libsql.saveExternalPorts": "write",
	"libsql.start": "write",
	"libsql.stop": "write",
	"libsql.update": "write",
	"licenseKey.activate": "write",
	"licenseKey.deactivate": "write",
	"licenseKey.getEnterpriseSettings": "read",
	"licenseKey.haveValidLicenseKey": "read",
	"licenseKey.updateEnterpriseSettings": "write",
	"licenseKey.validate": "write",
	"mariadb.changePassword": "write",
	"mariadb.changeStatus": "write",
	"mariadb.create": "write",
	"mariadb.deploy": "write",
	"mariadb.deployWithLogs": "write",
	"mariadb.move": "write",
	"mariadb.one": "read",
	"mariadb.readLogs": "read",
	"mariadb.rebuild": "write",
	"mariadb.reload": "write",
	"mariadb.remove": "dangerous",
	"mariadb.revealEnvironment": "dangerous",
	"mariadb.saveEnvironment": "write",
	"mariadb.saveExternalPort": "write",
	"mariadb.search": "read",
	"mariadb.start": "write",
	"mariadb.stop": "write",
	"mariadb.update": "write",
	"mongo.changePassword": "write",
	"mongo.changeStatus": "write",
	"mongo.create": "write",
	"mongo.deploy": "write",
	"mongo.deployWithLogs": "write",
	"mongo.move": "write",
	"mongo.one": "read",
	"mongo.readLogs": "read",
	"mongo.rebuild": "write",
	"mongo.reload": "write",
	"mongo.remove": "dangerous",
	"mongo.revealEnvironment": "dangerous",
	"mongo.saveEnvironment": "write",
	"mongo.saveExternalPort": "write",
	"mongo.search": "read",
	"mongo.start": "write",
	"mongo.stop": "write",
	"mongo.update": "write",
	"mounts.allNamedByApplicationId": "read",
	"mounts.create": "write",
	"mounts.listByServiceId": "read",
	"mounts.one": "read",
	"mounts.remove": "write",
	"mounts.update": "write",
	"mysql.changePassword": "write",
	"mysql.changeStatus": "write",
	"mysql.create": "write",
	"mysql.deploy": "write",
	"mysql.deployWithLogs": "write",
	"mysql.move": "write",
	"mysql.one": "read",
	"mysql.readLogs": "read",
	"mysql.rebuild": "write",
	"mysql.reload": "write",
	"mysql.remove": "dangerous",
	"mysql.revealEnvironment": "dangerous",
	"mysql.saveEnvironment": "write",
	"mysql.saveExternalPort": "write",
	"mysql.search": "read",
	"mysql.start": "write",
	"mysql.stop": "write",
	"mysql.update": "write",
	"network.all": "read",
	"network.create": "write",
	"network.import": "write",
	"network.inspect": "read",
	"network.networksToSync": "read",
	"network.one": "read",
	"network.recreate": "write",
	"network.remove": "write",
	"network.resync": "write",
	"notification.all": "read",
	"notification.createCustom": "dangerous",
	"notification.createDiscord": "dangerous",
	"notification.createEmail": "dangerous",
	"notification.createGotify": "dangerous",
	"notification.createLark": "dangerous",
	"notification.createMattermost": "dangerous",
	"notification.createNtfy": "dangerous",
	"notification.createPushover": "dangerous",
	"notification.createResend": "dangerous",
	"notification.createSlack": "dangerous",
	"notification.createTeams": "dangerous",
	"notification.createTelegram": "dangerous",
	"notification.getEmailProviders": "read",
	"notification.one": "read",
	"notification.receiveNotification": "write",
	"notification.remove": "dangerous",
	"notification.testCustomConnection": "write",
	"notification.testDiscordConnection": "write",
	"notification.testEmailConnection": "write",
	"notification.testGotifyConnection": "write",
	"notification.testLarkConnection": "write",
	"notification.testMattermostConnection": "write",
	"notification.testNtfyConnection": "write",
	"notification.testPushoverConnection": "write",
	"notification.testResendConnection": "write",
	"notification.testSlackConnection": "write",
	"notification.testTeamsConnection": "write",
	"notification.testTelegramConnection": "write",
	"notification.updateCustom": "dangerous",
	"notification.updateDiscord": "dangerous",
	"notification.updateEmail": "dangerous",
	"notification.updateGotify": "dangerous",
	"notification.updateLark": "dangerous",
	"notification.updateMattermost": "dangerous",
	"notification.updateNtfy": "dangerous",
	"notification.updatePushover": "dangerous",
	"notification.updateResend": "dangerous",
	"notification.updateSlack": "dangerous",
	"notification.updateTeams": "dangerous",
	"notification.updateTelegram": "dangerous",
	"organization.active": "read",
	"organization.all": "read",
	"organization.allInvitations": "read",
	"organization.create": "write",
	"organization.delete": "dangerous",
	"organization.inviteMember": "dangerous",
	"organization.one": "read",
	"organization.removeInvitation": "dangerous",
	"organization.setDefault": "write",
	"organization.update": "write",
	"organization.updateMemberRole": "dangerous",
	"overview.backups": "read",
	"overview.domains": "read",
	"overview.services": "read",
	"patch.byEntityId": "read",
	"patch.cleanPatchRepos": "write",
	"patch.create": "write",
	"patch.delete": "write",
	"patch.ensureRepo": "write",
	"patch.markFileForDeletion": "write",
	"patch.one": "read",
	"patch.readRepoDirectories": "read",
	"patch.readRepoFile": "read",
	"patch.saveFileAsPatch": "write",
	"patch.toggleEnabled": "write",
	"patch.update": "write",
	"port.create": "write",
	"port.delete": "write",
	"port.one": "read",
	"port.update": "write",
	"postgres.changePassword": "write",
	"postgres.changeStatus": "write",
	"postgres.create": "write",
	"postgres.deploy": "write",
	"postgres.deployWithLogs": "write",
	"postgres.move": "write",
	"postgres.one": "read",
	"postgres.readLogs": "read",
	"postgres.rebuild": "write",
	"postgres.reload": "write",
	"postgres.remove": "dangerous",
	"postgres.revealEnvironment": "dangerous",
	"postgres.saveEnvironment": "write",
	"postgres.saveExternalPort": "write",
	"postgres.search": "read",
	"postgres.start": "write",
	"postgres.stop": "write",
	"postgres.update": "write",
	"previewDeployment.all": "read",
	"previewDeployment.delete": "write",
	"previewDeployment.one": "read",
	"previewDeployment.redeploy": "write",
	"project.all": "read",
	"project.allForPermissions": "read",
	"project.completeOnboarding": "write",
	"project.create": "write",
	"project.duplicate": "write",
	"project.homeStats": "read",
	"project.onboardingStatus": "read",
	"project.one": "read",
	"project.remove": "dangerous",
	"project.search": "read",
	"project.update": "write",
	"redirects.create": "write",
	"redirects.delete": "write",
	"redirects.one": "read",
	"redirects.update": "write",
	"redis.changePassword": "write",
	"redis.changeStatus": "write",
	"redis.create": "write",
	"redis.deploy": "write",
	"redis.deployWithLogs": "write",
	"redis.move": "write",
	"redis.one": "read",
	"redis.readLogs": "read",
	"redis.rebuild": "write",
	"redis.reload": "write",
	"redis.remove": "dangerous",
	"redis.revealEnvironment": "dangerous",
	"redis.saveEnvironment": "write",
	"redis.saveExternalPort": "write",
	"redis.search": "read",
	"redis.start": "write",
	"redis.stop": "write",
	"redis.update": "write",
	"registry.all": "read",
	"registry.create": "write",
	"registry.one": "read",
	"registry.remove": "dangerous",
	"registry.testRegistry": "write",
	"registry.testRegistryById": "write",
	"registry.update": "write",
	"rollback.delete": "write",
	"rollback.rollback": "write",
	"schedule.create": { dangerousWhen: isHostScheduleInput },
	"schedule.delete": "write",
	"schedule.list": "read",
	"schedule.one": "read",
	"schedule.runManually": { dangerousWhen: isStoredHostSchedule },
	"schedule.update": { dangerousWhen: isStoredHostSchedule },
	"scim.createConnection": "dangerous",
	"scim.decommissionConnection": "dangerous",
	"scim.events": "read",
	"scim.listConnections": "read",
	"scim.revokeCredential": "dangerous",
	"scim.rotateCredential": "dangerous",
	"security.create": "write",
	"security.delete": "write",
	"security.one": "read",
	"security.update": "write",
	"server.all": "read",
	"server.allForPermissions": "read",
	"server.buildServers": "read",
	"server.count": "read",
	"server.create": "dangerous",
	"server.getContainerProcesses": "read",
	"server.getContainerResourceStats": "read",
	"server.getDefaultCommand": "read",
	"server.getServerMetrics": "read",
	"server.getServerTime": "read",
	"server.getServices": "read",
	"server.one": "read",
	"server.publicIp": "read",
	"server.remove": "dangerous",
	"server.security": "read",
	"server.setup": "write",
	"server.setupMonitoring": "write",
	"server.setupWithLogs": "write",
	"server.update": "dangerous",
	"server.updateBuildsConcurrency": "write",
	"server.validate": "read",
	"server.withSSHKey": "read",
	"settings.assignDomainServer": "dangerous",
	"settings.checkGPUStatus": "read",
	"settings.checkInfrastructureHealth": "read",
	"settings.cleanAll": "write",
	"settings.cleanAllDeploymentQueue": "write",
	"settings.cleanDockerBuilder": "write",
	"settings.cleanDockerPrune": "write",
	"settings.cleanMonitoring": "write",
	"settings.cleanSSHPrivateKey": "dangerous",
	"settings.cleanStoppedContainers": "write",
	"settings.cleanUnusedImages": "write",
	"settings.cleanUnusedVolumes": "dangerous",
	"settings.getDockerDiskUsage": "read",
	"settings.getDokployCloudIps": "read",
	"settings.getDokployVersion": "read",
	"settings.getDokployVersionData": "read",
	"settings.getIp": "read",
	"settings.getLogCleanupStatus": "read",
	"settings.getOpenApiDocument": "read",
	"settings.getReleaseTag": "read",
	"settings.getTraefikPorts": "read",
	"settings.getUpdateData": "write",
	"settings.getWebServerSettings": "read",
	"settings.haveActivateRequests": "read",
	"settings.haveTraefikDashboardPortEnabled": "read",
	"settings.health": "read",
	"settings.isCloud": "read",
	"settings.isUserSubscribed": "read",
	"settings.readDirectories": "read",
	"settings.readMiddlewareTraefikConfig": "read",
	"settings.readStats": "read",
	"settings.readStatsLogs": "read",
	"settings.readTraefikConfig": "read",
	"settings.readTraefikEnv": "dangerous",
	"settings.readTraefikFile": "read",
	"settings.readWebServerTraefikConfig": "read",
	"settings.reloadServer": "dangerous",
	"settings.reloadTraefik": "write",
	"settings.saveSSHPrivateKey": "dangerous",
	"settings.setupGPU": "write",
	"settings.toggleDashboard": "dangerous",
	"settings.toggleRequests": "write",
	"settings.updateBuildsConcurrency": "write",
	"settings.updateDockerCleanup": "write",
	"settings.updateEnforceSSO": "dangerous",
	"settings.updateLogCleanup": "write",
	"settings.updateMiddlewareTraefikConfig": "dangerous",
	"settings.updateRemoteServersOnly": "write",
	"settings.updateServer": "dangerous",
	"settings.updateServerIp": "dangerous",
	"settings.updateTraefikConfig": "dangerous",
	"settings.updateTraefikFile": "dangerous",
	"settings.updateTraefikPorts": "dangerous",
	"settings.updateWebServerTraefikConfig": "dangerous",
	"settings.writeTraefikEnv": "dangerous",
	"sshKey.all": "read",
	"sshKey.allForApps": "read",
	"sshKey.create": "dangerous",
	"sshKey.generate": "write",
	"sshKey.one": "read",
	"sshKey.remove": "dangerous",
	"sshKey.update": "dangerous",
	"sso.addTrustedOrigin": "dangerous",
	"sso.deleteProvider": "dangerous",
	"sso.enforceSSO": "read",
	"sso.getTrustedOrigins": "read",
	"sso.listProviders": "read",
	"sso.one": "read",
	"sso.register": "dangerous",
	"sso.removeTrustedOrigin": "dangerous",
	"sso.showSignInWithSSO": "read",
	"sso.update": "dangerous",
	"sso.updateTrustedOrigin": "dangerous",
	"stripe.canCreateMoreServers": "read",
	"stripe.createCheckoutSession": "write",
	"stripe.createCustomerPortalSession": "write",
	"stripe.getBillingStatus": "read",
	"stripe.getCurrentPlan": "read",
	"stripe.getInvoices": "read",
	"stripe.getProducts": "read",
	"stripe.startFreeTrial": "write",
	"stripe.updateInvoiceNotifications": "write",
	"stripe.upgradeSubscription": "write",
	"superPassword.change": "write",
	"superPassword.close": "write",
	"superPassword.disable": "write",
	"superPassword.extend": "write",
	"superPassword.lockWithToken": "write",
	"superPassword.requestReset": "write",
	"superPassword.resetWithToken": "write",
	"superPassword.set": "write",
	"superPassword.status": "read",
	"superPassword.unlock": "write",
	"swarm.getAppInfos": "read",
	"swarm.getContainerStats": "read",
	"swarm.getNodeApps": "read",
	"swarm.getNodeInfo": "read",
	"swarm.getNodes": "read",
	"tag.all": "read",
	"tag.assignToProject": "write",
	"tag.bulkAssign": "write",
	"tag.create": "write",
	"tag.one": "read",
	"tag.remove": "write",
	"tag.removeFromProject": "write",
	"tag.update": "write",
	"transfer.start": "write",
	"user.all": "read",
	"user.assignPermissions": "dangerous",
	"user.checkUserOrganizations": "read",
	"user.createApiKey": "dangerous",
	"user.createUserWithCredentials": "dangerous",
	"user.deleteAccount": "dangerous",
	"user.deleteAccountByEmail": "dangerous",
	"user.deleteApiKey": "dangerous",
	"user.generateToken": "write",
	"user.get": "read",
	"user.getBackups": "read",
	"user.getBookmarkedTemplates": "read",
	"user.getContainerMetrics": "read",
	"user.getInvitations": "read",
	"user.getMetricsToken": "read",
	"user.getPermissions": "read",
	"user.getServerMetrics": "read",
	"user.getUserByToken": "read",
	"user.hasPassword": "read",
	"user.haveRootAccess": "read",
	"user.listPasskeys": "read",
	"user.listSessions": "read",
	"user.one": "read",
	"user.remove": "dangerous",
	"user.requestAccountDeletionCode": "write",
	"user.revokeSession": "write",
	"user.sendInvitation": "dangerous",
	"user.session": "read",
	"user.toggleTemplateBookmark": "write",
	"user.update": { dangerousWhen: changesLoginCredentials },
	"vaultProvider.all": "read",
	"vaultProvider.create": "write",
	"vaultProvider.listSecretNames": "read",
	"vaultProvider.one": "read",
	"vaultProvider.remove": "write",
	"vaultProvider.testConnection": "write",
	"vaultProvider.update": "write",
	"volumeBackups.create": "write",
	"volumeBackups.delete": "write",
	"volumeBackups.list": "read",
	"volumeBackups.one": "read",
	"volumeBackups.restoreVolumeBackupWithLogs": "dangerous",
	"volumeBackups.runManually": "write",
	"volumeBackups.update": "write",
	"whitelabeling.get": "read",
	"whitelabeling.getPublic": "read",
	"whitelabeling.reset": "write",
	"whitelabeling.update": "write",
};

export const resolveProcedureAccess = async ({
	path,
	type,
	getRawInput,
	ctx,
}: {
	path: string;
	type: "query" | "mutation" | "subscription";
	getRawInput: () => Promise<unknown>;
	ctx: ProcedureAccessCtx;
}): Promise<SuperSessionAccessKind> => {
	const access = PROCEDURE_ACCESS[path];
	const byType: SuperSessionAccessKind = type === "query" ? "read" : "write";

	// A mutation or subscription is never weaker than a write, whatever the
	// table says, and unknown procedures fall back to their type.
	if (access === undefined || access === "read") {
		return byType;
	}
	if (typeof access === "string") {
		return access;
	}
	return (await access.dangerousWhen(await getRawInput(), ctx))
		? "dangerous"
		: byType;
};
